### ISSUE TITLE
DLA Cores for Jetson

### ISSUE THREAD

**Issue by sanketgoyal** [yuefanhao/SuperPoint-SuperGlue-TensorRT#30]
Hello, I would like to understand if the code runs on DLA cores or not? Even after changing the settings for dla_cores from -1 to 0 or 1, for a jetson device, I see no improvement in the model. When looking at the clock frequencies of the two cores, they are shown inactive on a nvidia jetson device.

**Comment by bgatten** [comment]
Same issue here - Seems like this would give a nice performance bump if it were working

**Comment by yuefanhao** [comment]
Thanks for reporting the issue. I followed NVIDIA's API and set DLA_Core in the TensorRT Builder Config. I'm not sure why it does not work. I think you could re-direct this question to NVIDIA.

**Comment by yrq0208** [comment]
might be a bit late to this...but using the provided pretrained onnx models, I believe superpoint does not use DLA whereas some of the superglue layers can be run on DLA. You can look at the attached profile log for more details. The reason why superpoint and some of the superglue layers are not run on DLA is because they are not supported.
[superglue.log](https://github.com/user-attachments/files/16359592/superglue.log)
[superpoint.log](https://github.com/user-attachments/files/16359593/superpoint.log)
