### ISSUE TITLE
SuperGlue part cannot give any feature point matches

### ISSUE THREAD

**Issue by ChangenicRM** [yuefanhao/SuperPoint-SuperGlue-TensorRT#7]
After: 
`superglue->matching_points(feature_points0, feature_points1, superglue_matches);`
There is no matching result.
Then I go to check the condition:
`if (indices0(i) < indices1.size() && indices0(i) >= 0 && indices1(indices0(i)) == i)`
but indices0(i) are always equal to -1
So, could you please give some advice about this? Thanks.

**Comment by ChangenicRM** [comment]
OK, now problem solved. My tensorRT version is too high. Now I will change it into older version.

**Comment by Mediumcore** [comment]
![match_image](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/assets/16093691/e608f4bd-05a9-4377-aa4c-094131a679a7)
Hello,same problem,I think tensorrt version is not the good solution, how to solve this by modifying code?

**Comment by eshafeeqe** [comment]
Hello, 

I came across same problem, any idea how to fix this without downgrading the tensorrt version ?

**Comment by weihaoysgs** [comment]
Hello, I also encounter this problem, but i can not downgrading the tensorrt version because of other application using the  high version of tensorrt, so if there any other idea to solve this problem?

**Comment by Mediumcore** [comment]
can install different trt versions in different folders.



---Original---
From: ***@***.***&gt;
Date: Sun, Dec 17, 2023 22:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yuefanhao/SuperPoint-SuperGlue-TensorRT] SuperGlue part cannotgive any feature point matches (Issue #7)




 
Hello, I also encounter this problem, but i can not downgrading the tensorrt version because of other application using the  high version of tensorrt, so if there any other idea to solve this problem?

**Comment by fettahyildizz** [comment]
Why does higher tensorrt version create issue with the model?
